In [1]:
import CASBI
import CASBI.utils as utils
from CASBI.generator import *
import pandas as pd

In [2]:
path_train_dataframe = '../../data/dataframe/dataframe.parquet'
test_and_nll_path = '../../data/test_and_nll/'

In [3]:
utils.distributed_training(path_train_dataframe=path_train_dataframe, 
                           test_and_nll_path=test_and_nll_path, 
                           world_size = 4,   
                           batch_size = 1024,
                           number_of_epochs = 10)

W0508 09:56:20.556000 140475306471808 torch/distributed/run.py:757] 
W0508 09:56:20.556000 140475306471808 torch/distributed/run.py:757] *****************************************
W0508 09:56:20.556000 140475306471808 torch/distributed/run.py:757] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0508 09:56:20.556000 140475306471808 torch/distributed/run.py:757] *****************************************


           feh       ofe  ...  std_OMassFrac     Galaxy_name
0    -2.241043  2.657175  ...      -0.612057  g6.31e09.00032
1    -1.968656  2.641414  ...      -0.612057  g6.31e09.00032
2    -1.316400  2.849783  ...      -0.612057  g6.31e09.00032
3    -2.084684  2.886502  ...      -0.612057  g6.31e09.00032
4    -3.363201  2.616445  ...      -0.612057  g6.31e09.00032
...        ...       ...  ...            ...             ...
4995  1.857773  0.037136  ...       2.594511  g3.21e11.01024
4996 -0.614566  0.484494  ...       2.594511  g3.21e11.01024
4997  1.566647  0.190610  ...       2.594511  g3.21e11.01024
4998  0.762806  0.436909  ...       2.594511  g3.21e11.01024
4999  2.036695 -0.059360  ...       2.594511  g3.21e11.01024

[14965 rows x 11 columns]
           feh       ofe  ...  std_OMassFrac     Galaxy_name
0    -2.241043  2.657175  ...      -0.612057  g6.31e09.00032
1    -1.968656  2.641414  ...      -0.612057  g6.31e09.00032
2    -1.316400  2.849783  ...      -0.612057  g6.31e09.000

KeyboardInterrupt: 

tensor([[-1.6331e-01,  3.5243e-01, -4.5463e-02,  ..., -4.9257e-01,
         -5.2415e-01, -5.1858e-01],
        [ 1.3166e+00, -3.0741e-01,  1.0359e+00,  ...,  3.4231e-01,
          3.8743e-01,  3.7505e-01],
        [ 4.3847e-01, -6.2383e-01, -7.0714e-04,  ..., -3.9388e-01,
         -3.9781e-01, -4.0431e-01],
        ...,
        [-2.1061e-01, -2.4081e-01, -6.1474e-01,  ..., -5.2886e-01,
         -5.4805e-01, -5.4884e-01],
        [-1.7013e-01, -1.5592e+00, -1.3396e+00,  ..., -6.2312e-01,
         -5.5586e-01, -5.6485e-01],
        [-3.4015e+00,  2.5114e+00, -2.3547e+00,  ..., -6.8767e-01,
         -6.2017e-01, -6.1206e-01]], device='cuda:0', dtype=torch.float64)
batch_loss 1.5117383003234863
tensor([[-0.4010,  0.1474, -1.2839,  ..., -0.5996, -0.5610, -0.5636],
        [-0.0297, -0.6336, -0.4953,  ..., -0.5237, -0.5579, -0.5586],
        [ 1.4177, -0.3505,  1.0359,  ...,  0.3423,  0.3874,  0.3750],
        ...,
        [-1.7796,  2.4221, -2.3547,  ..., -0.6877, -0.6202, -0.6121],
       

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
    self._run()
  File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 275, in _run
    self._record_writer.write(data)
  File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 773, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/export/home/vgiusepp/miniconda

tensor([[-2.7658,  2.7575, -1.2839,  ..., -0.5996, -0.5610, -0.5636],
        [ 0.2371,  0.8465,  0.9773,  ..., -0.0211, -0.0915, -0.0810],
        [ 0.4626, -1.6446, -1.1347,  ..., -0.5659, -0.5345, -0.5402],
        ...,
        [-0.0758, -1.1701, -1.1347,  ..., -0.5659, -0.5345, -0.5402],
        [-0.2089, -0.0717,  0.3195,  ..., -0.4301, -0.4535, -0.4459],
        [ 0.0292, -1.1640,  1.5799,  ...,  2.6855,  2.6042,  2.5945]],
       device='cuda:2', dtype=torch.float64)
batch_loss 1.3817260265350342
tensor([[ 0.4517, -1.2434, -0.0784,  ..., -0.3621, -0.3117, -0.3233],
        [-1.6389,  1.1535, -1.4236,  ..., -0.6349, -0.5695, -0.5662],
        [-1.6152,  0.6734, -0.3935,  ..., -0.5348, -0.5231, -0.5247],
        ...,
        [ 0.9548, -1.0634, -0.0784,  ..., -0.3621, -0.3117, -0.3233],
        [-1.5348,  1.4541, -1.0106,  ..., -0.5219, -0.5124, -0.5208],
        [ 0.4706,  0.9851,  1.5498,  ...,  2.3853,  1.8966,  1.8995]],
       device='cuda:3', dtype=torch.float64)
batch_loss 1

[rank0]: Traceback (most recent call last):
[rank0]:   File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/site-packages/CASBI/distributed_training.py", line 307, in <module>
[rank0]:     end = time.time()
[rank0]:   File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/site-packages/CASBI/distributed_training.py", line 288, in main
[rank0]:     negative_log_likelihood = trainer.test(test_data)
[rank0]:   File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/site-packages/CASBI/distributed_training.py", line 175, in train
[rank0]:     val_running_loss = self._run_epoch(epoch)
[rank0]:   File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/site-packages/CASBI/distributed_training.py", line 157, in _run_epoch
[rank0]:     self.logger.add_scalar("Loss/val", val_running_loss/int(os.environ["WORLD_SIZE"]), epoch) #the WORLD_SIZE is the number of GPUs
[rank0]:   File "/export/home/vgiusepp/miniconda3/envs/test/lib/python3.10/site-packages/torch/util